# Generated by Django 6.0.6 on 2026-06-26 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالفرنسية')),
                ('color', models.CharField(default='#0f172a', max_length=10, verbose_name='اللون (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'فرع مهني',
                'verbose_name_plural': '📚 الفروع المهنية',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='التعليق (alt)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': '🖼️ معرض الصور (Carousel)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='مثال: 15 أو +500', max_length=30, verbose_name='القيمة')),
                ('label', models.CharField(help_text='مثال: فرعا', max_length=80, verbose_name='التسمية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'إحصائية',
                'verbose_name_plural': '📊 إحصائيات الصفحة الرئيسية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InternalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='العنوان الفرعي')),
                ('icon_class', models.CharField(default='bi bi-app', max_length=60, verbose_name='أيقونة Bootstrap')),
                ('url', models.CharField(max_length=255, verbose_name='الرابط')),
                ('color', models.CharField(choices=[('amber', 'أصفر (amber)'), ('teal', 'أخضر مائي (teal)'), ('blue', 'أزرق (blue)')], default='amber', max_length=20, verbose_name='اللون')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='فتح في نافذة جديدة')),
                ('show_in_navbar', models.BooleanField(default=True, verbose_name='إظهار في شريط التصفح')),
                ('show_in_hero', models.BooleanField(default=True, verbose_name='إظهار في الهيرو')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='إظهار في التذييل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تطبيق داخلي',
                'verbose_name_plural': '🧩 التطبيقات الداخلية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi bi-bullseye', help_text='مثال: bi bi-bullseye', max_length=60, verbose_name='أيقونة Bootstrap')),
                ('color', models.CharField(choices=[('amber', 'أصفر (amber)'), ('green', 'أخضر (green)'), ('blue', 'أزرق (blue)')], default='amber', max_length=20, verbose_name='اللون')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('text', models.TextField(verbose_name='النص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بطاقة هوية',
                'verbose_name_plural': '🪪 بطاقات الهوية المؤسسية (مهمتنا/رؤيتنا/كفاءاتنا)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='التسمية')),
                ('url', models.CharField(max_length=255, verbose_name='الرابط')),
                ('icon_class', models.CharField(default='bi bi-chevron-left', max_length=60, verbose_name='أيقونة Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رابط تصفح',
                'verbose_name_plural': '🧭 روابط التصفح (التذييل)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='إيمس', max_length=120, verbose_name='اسم المؤسسة')),
                ('site_full_name', models.CharField(default='مؤسسة التميز للإدارة والأمن', max_length=200, verbose_name='الاسم الكامل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='الشعار')),
                ('browser_title', models.CharField(default='إيمس — مؤسسة التميز للإدارة والأمن', max_length=200, verbose_name='عنوان المتصفح')),
                ('hero_badge_text', models.CharField(blank=True, default='معتمدة من وزارة التكوين والتعليم المهنيين', max_length=150, verbose_name='شارة الهيرو')),
                ('hero_title_line1', models.CharField(default='مؤسسة التميز', max_length=150, verbose_name='العنوان - السطر 1')),
                ('hero_title_line2', models.CharField(default='للإدارة', max_length=150, verbose_name='العنوان - السطر 2')),
                ('hero_title_accent', models.CharField(default='والأمن', max_length=150, verbose_name='العنوان - الكلمة المميزة')),
                ('hero_description', models.TextField(blank=True, verbose_name='وصف الهيرو')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='صورة الهيرو')),
                ('hero_cta_primary_text', models.CharField(default='اطّلع على تكويناتنا', max_length=80, verbose_name='زر أساسي - نص')),
                ('hero_cta_primary_url', models.CharField(default='#formations', max_length=200, verbose_name='زر أساسي - رابط')),
                ('hero_cta_secondary_text', models.CharField(default='التصنيف الرسمي', max_length=80, verbose_name='زر ثانوي - نص')),
                ('hero_cta_secondary_url', models.CharField(default='nomenclature/', max_length=200, verbose_name='زر ثانوي - رابط')),
                ('formations_label', models.CharField(default='الكتالوج الرسمي 2019', max_length=100, verbose_name='التكوينات - تسمية')),
                ('formations_title', models.CharField(default='23 فرعا مهنيا', max_length=150, verbose_name='التكوينات - عنوان')),
                ('formations_description', models.TextField(blank=True, verbose_name='التكوينات - وصف')),
                ('video_label', models.CharField(default='اكتشف', max_length=100, verbose_name='الفيديو - تسمية')),
                ('video_title', models.CharField(default='المسير العملي', max_length=150, verbose_name='الفيديو - عنوان')),
                ('video_description', models.TextField(blank=True, verbose_name='الفيديو - وصف')),
                ('video_youtube_embed_url', models.URLField(blank=True, verbose_name='رابط يوتيوب (embed)')),
                ('gallery_label', models.CharField(default='معرض الصور', max_length=100, verbose_name='المعرض - تسمية')),
                ('gallery_title', models.CharField(default='مرحبا بكم في إيمس', max_length=150, verbose_name='المعرض - عنوان')),
                ('map_label', models.CharField(default='الموقع', max_length=100, verbose_name='الموقع - تسمية')),
                ('map_title', models.CharField(default='كيف تجدنا', max_length=150, verbose_name='الموقع - عنوان')),
                ('map_description', models.TextField(blank=True, verbose_name='الموقع - وصف')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='رابط خريطة Google (embed)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='أوقات العمل')),
                ('footer_description', models.TextField(blank=True, verbose_name='وصف التذييل')),
                ('footer_copyright', models.CharField(default='© 2025 إيمس — مؤسسة التميز للإدارة والأمن — جميع الحقوق محفوظة.', max_length=200, verbose_name='حقوق النشر')),
                ('footer_location_text', models.CharField(blank=True, default='سطيف، الجزائر', max_length=150, verbose_name='موقع التذييل')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': '⚙️ إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('email', 'Email'), ('other', 'أخرى')], max_length=20, verbose_name='المنصة')),
                ('url', models.CharField(max_length=255, verbose_name='الرابط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رابط اجتماعي',
                'verbose_name_plural': '🔗 الروابط الاجتماعية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التخصص')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='pages.branch', verbose_name='الفرع المهني')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': '🗂️ التخصصات (الكتالوج الرسمي 2019)',
                'ordering': ['branch__order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('start_date', models.DateField(verbose_name='تاريخ الانطلاق')),
                ('duration_text', models.CharField(help_text='مثال: 5 أيام', max_length=50, verbose_name='المدة')),
                ('seats', models.PositiveIntegerField(verbose_name='عدد المقاعد')),
                ('status', models.CharField(choices=[('planned', 'مبرمجة'), ('open', 'التسجيل مفتوح')], default='planned', max_length=10, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة (تظهر في الصفحة)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pages.branch', verbose_name='الفرع المهني')),
            ],
            options={
                'verbose_name': 'دورة قادمة',
                'verbose_name_plural': '🗓️ الدورات القادمة',
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
