# Generated by Django 6.0.3 on 2026-06-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter / X'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('youtube', 'YouTube'), ('email', 'Email'), ('other', 'أخرى')], max_length=20, verbose_name='المنصة'),
        ),
    ]
