# Generated by Django 6.0.3 on 2026-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط خريطة Google (embed)'),
        ),
    ]
