# Generated by Django 6.0.3 on 2026-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='video_youtube_embed_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/1h4-kRB8OjA?si=6XjJKFKHlIqeWta_', verbose_name='رابط يوتيوب (embed)'),
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64, verbose_name='هاش IP')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': '📈 إحصائيات الزوار',
                'ordering': ['-date'],
                'unique_together': {('ip_hash', 'date')},
            },
        ),
    ]
