# Generated by Django 5.0.6 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_sitesettings_video_youtube_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
            options={
                'verbose_name': 'مشترك في النشرة',
                'verbose_name_plural': '📩 المشتركون في النشرة الإخبارية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='الشعار')),
                ('url', models.URLField(blank=True, verbose_name='الرابط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'شريك / جهة اعتماد',
                'verbose_name_plural': '🤝 الشركاء وجهات الاعتماد',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi bi-1-circle', max_length=60, verbose_name='أيقونة Bootstrap')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خطوة',
                'verbose_name_plural': '🪜 كيف نعمل (خطوات التسجيل)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='الصفة / المؤسسة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='الصورة')),
                ('quote', models.TextField(verbose_name='الشهادة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'شهادة نجاح',
                'verbose_name_plural': '💬 شهادات النجاح',
                'ordering': ['order', 'id'],
            },
        ),
    ]
