# Generated by Django 6.0.7 on 2026-07-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_newslettersubscriber_partner_processstep_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(blank=True, default='من نحن', max_length=100, verbose_name='شارة الصفحة')),
                ('hero_title', models.CharField(default='قصة مؤسسة التميز للإدارة والأمن', max_length=200, verbose_name='عنوان الصفحة')),
                ('hero_description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/about/', verbose_name='صورة الصفحة')),
                ('story_label', models.CharField(blank=True, default='قصتنا', max_length=100, verbose_name='قصتنا - تسمية')),
                ('story_title', models.CharField(blank=True, default='كيف بدأنا', max_length=200, verbose_name='قصتنا - عنوان')),
                ('story_body', models.TextField(blank=True, verbose_name='قصتنا - نص')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='site/about/', verbose_name='قصتنا - صورة')),
                ('values_label', models.CharField(blank=True, default='قيمنا', max_length=100, verbose_name='القيم - تسمية')),
                ('values_title', models.CharField(blank=True, default='ما الذي يميزنا', max_length=200, verbose_name='القيم - عنوان')),
                ('timeline_label', models.CharField(blank=True, default='مسارنا', max_length=100, verbose_name='المسار الزمني - تسمية')),
                ('timeline_title', models.CharField(blank=True, default='محطات بارزة', max_length=200, verbose_name='المسار الزمني - عنوان')),
            ],
            options={
                'verbose_name': 'صفحة من نحن',
                'verbose_name_plural': '📖 صفحة من نحن',
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi bi-gem', max_length=60, verbose_name='أيقونة Bootstrap')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('text', models.TextField(verbose_name='النص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قيمة',
                'verbose_name_plural': '💎 قيم المؤسسة (صفحة من نحن)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('subject', models.CharField(choices=[('info', 'طلب معلومات عن التكوينات'), ('enrollment', 'استفسار حول التسجيل'), ('partnership', 'شراكة / تعاون'), ('complaint', 'شكوى / ملاحظة'), ('other', 'أخرى')], default='info', max_length=20, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('read', 'مقروءة'), ('replied', 'تم الرد')], default='new', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': '✉️ رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='تواصل معنا', max_length=100, verbose_name='تسمية')),
                ('title', models.CharField(blank=True, default='نحن هنا لمساعدتك', max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
            ],
            options={
                'verbose_name': 'إعدادات صفحة الاتصال',
                'verbose_name_plural': '☎️ إعدادات صفحة الاتصال',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الفئة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فئة أسئلة',
                'verbose_name_plural': '🗂️ فئات الأسئلة الشائعة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='السنة')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('text', models.TextField(blank=True, verbose_name='النص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'محطة',
                'verbose_name_plural': '🏁 المسار الزمني (صفحة من نحن)',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الجواب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.faqcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': '❓ الأسئلة الشائعة',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
    ]
