# Generated by Django 6.0.7 on 2026-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpage_aboutvalue_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='icon_class',
            field=models.CharField(default='bi bi-question-circle', max_length=60, verbose_name='أيقونة Bootstrap'),
        ),
    ]
