# Generated by Django 6.1 on 2026-08-23 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_faqcategory_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='epilogue_video',
            field=models.FileField(blank=True, help_text='MP4 / WebM / MOV — إن تُرك فارغا يُستعمل الفيديو الافتراضي المرفق بالموقع.', null=True, upload_to='site/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])], verbose_name='فيديو الخاتمة (Epilogue)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prologue_video',
            field=models.FileField(blank=True, help_text='MP4 / WebM / MOV — إن تُرك فارغا يُستعمل الفيديو الافتراضي المرفق بالموقع.', null=True, upload_to='site/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])], verbose_name='فيديو المقدمة (Prologue)'),
        ),
    ]
