# Generated by Django 4.2.30 on 2026-07-26 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_alter_sitesettings_video_youtube_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الدورة')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف (slug)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانطلاق')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='آخر أجل للتسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفتوحة للتسجيل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'دورة تكوينية',
                'verbose_name_plural': 'الدورات التكوينية',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: TAG0701', max_length=20, verbose_name='رمز الاختصاص')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان التخصص')),
                ('branch_label', models.CharField(blank=True, max_length=100, verbose_name='الشعبة')),
                ('qualification_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - شهادة تكوين مهني متخصص (ش.م.ت.م)'), (2, '2 - شهادة الكفاءة المهنية (ش.ك.م)'), (3, '3 - شهادة التحكم المهني (ش.ت.م)'), (4, '4 - شهادة تقني (ش.ت)'), (5, '5 - شهادة تقني سامي (ش.ت.س)')], null=True, verbose_name='مستوى التأهيل')),
                ('certificate_type', models.CharField(blank=True, choices=[('qualification', 'شهادة تأهيل مهني'), ('cfpm', 'شهادة تكوين مهني متخصص'), ('cap', 'شهادة الكفاءة المهنية'), ('bpm', 'شهادة التحكم المهني'), ('tech', 'شهادة تقني'), ('tech_sup', 'شهادة تقني سامي')], max_length=20, verbose_name='الشهادة المسلمة')),
                ('entry_level', models.CharField(blank=True, choices=[('none', 'بدون مستوى / محو أمية منتهي'), ('middle4', '4 متوسط'), ('sec1', '1 ثانوي'), ('sec2', '2 ثانوي'), ('sec3', '3 ثانوي')], max_length=20, verbose_name='مستوى الدخول')),
                ('duration_months', models.PositiveSmallIntegerField(verbose_name='مدة التكوين (أشهر)')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الشهرية (دج)')),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الإجمالية (دج)')),
                ('seats_available', models.PositiveSmallIntegerField(default=0, verbose_name='قدرة الاستيعاب')),
                ('description', models.TextField(blank=True, verbose_name='تعريف التخصص')),
                ('main_tasks', models.TextField(blank=True, help_text='سطر واحد لكل مهمة', verbose_name='المهام الأساسية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='enrollment/offerings/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='معروضة على الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='enrollment.formationsession', verbose_name='الدورة')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='pages.specialty', verbose_name='التخصص (مدونة الشعب)')),
            ],
            options={
                'verbose_name': 'عرض تكوين',
                'verbose_name_plural': 'عروض التكوين',
                'ordering': ['order', 'code'],
                'unique_together': {('session', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم واللقب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='المستوى الدراسي')),
                ('wilaya', models.CharField(blank=True, default='سطيف', max_length=60, verbose_name='الولاية')),
                ('motivation', models.TextField(blank=True, verbose_name='ملاحظات / دافع الترشح')),
                ('source', models.CharField(choices=[('web', 'الموقع الإلكتروني'), ('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('qr', 'QR Code'), ('phone', 'اتصال هاتفي'), ('walkin', 'حضور مباشر')], default='web', max_length=20, verbose_name='مصدر التسجيل')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('contacted', 'تم التواصل'), ('accepted', 'مقبول'), ('waitlisted', 'قائمة انتظار'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عولجت من طرف')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='enrollment.offering', verbose_name='التخصص المطلوب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollment.subscription')),
            ],
            options={
                'verbose_name': 'ملاحظة متابعة',
                'verbose_name_plural': 'ملاحظات المتابعة',
                'ordering': ['created_at'],
            },
        ),
    ]
