# Generated by Django 4.2.30 on 2026-07-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'فرد (خاص)'), ('enterprise', 'مؤسسة')], default='individual', max_length=20, verbose_name='نوع الزبون')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('wilaya', models.CharField(blank=True, default='سطيف', max_length=60, verbose_name='الولاية')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم واللقب')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='المستوى الدراسي')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤسسة')),
                ('trade_register_number', models.CharField(blank=True, max_length=60, verbose_name='رقم السجل التجاري')),
                ('sector', models.CharField(blank=True, max_length=120, verbose_name='قطاع النشاط')),
                ('responsible_name', models.CharField(blank=True, max_length=150, verbose_name='الشخص المسؤول عن التنسيق')),
                ('responsible_position', models.CharField(blank=True, max_length=100, verbose_name='منصب المسؤول')),
                ('source', models.CharField(choices=[('web', 'الموقع الإلكتروني'), ('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('qr', 'QR Code'), ('phone', 'اتصال هاتفي'), ('walkin', 'حضور مباشر')], default='web', max_length=20, verbose_name='مصدر التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'زبون (مشترك)',
                'verbose_name_plural': 'الزبائن (المشتركون)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, verbose_name='ملاحظات / دافع الترشح')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('contacted', 'تم التواصل'), ('accepted', 'مقبول'), ('waitlisted', 'قائمة انتظار'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.client', verbose_name='الزبون')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عولجت من طرف')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.offering', verbose_name='التخصص المطلوب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollment.enrollment')),
            ],
            options={
                'verbose_name': 'ملاحظة متابعة',
                'verbose_name_plural': 'ملاحظات المتابعة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم واللقب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='المستوى الدراسي')),
                ('position', models.CharField(blank=True, help_text='يُستعمل فقط عندما يكون الزبون مؤسسة', max_length=100, verbose_name='المنصب داخل المؤسسة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='enrollment.client', verbose_name='الزبون')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['full_name'],
            },
        ),
        migrations.RemoveField(
            model_name='subscriptionnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscriptionnote',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionNote',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.participant', verbose_name='المشارك'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('participant', 'offering')},
        ),
    ]
