# Generated by Django 5.0.6 on 2026-07-27 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_client_enrollment_enrollmentnote_participant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='تخصص مميز (يظهر في الصفحة الرئيسية)'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='التقييم')),
                ('text', models.TextField(verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه (يظهر في الموقع)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enrollment.offering', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'تعليقات الزوار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('question', models.TextField(verbose_name='السؤال / الاستفسار')),
                ('answer', models.TextField(blank=True, verbose_name='الرد')),
                ('is_answered', models.BooleanField(default=False, verbose_name='تمت الإجابة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أجاب عليه')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='enrollment.offering', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'استفسار',
                'verbose_name_plural': 'استفسارات الزوار',
                'ordering': ['-created_at'],
            },
        ),
    ]
