# Generated by Django 6.0.7 on 2026-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_offering_is_featured_comment_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='background_url',
            field=models.URLField(blank=True, help_text='تُعرض كخلفية لرأس صفحة التخصص.', verbose_name='رابط صورة الخلفية (صفحة التفاصيل)'),
        ),
        migrations.AddField(
            model_name='offering',
            name='poster_url',
            field=models.URLField(blank=True, help_text='يُستعمل إن لم يتم رفع صورة أعلاه. يمكن استعمال رابط من خدمة صور مجانية.', verbose_name='رابط صورة الملصق (بطاقة العرض)'),
        ),
        migrations.AddField(
            model_name='offering',
            name='video_url',
            field=models.URLField(blank=True, help_text='ألصق رابط فيديو يوتيوب ترويجي لهذا التخصص (اختياري).', verbose_name='رابط فيديو تعريفي (YouTube)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enrollment/offerings/', verbose_name='صورة (ملف مرفوع)'),
        ),
    ]
