# Generated by Django 6.0.7 on 2026-07-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_offering_background_url_offering_poster_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='المعرف (slug)')),
                ('title', models.CharField(blank=True, help_text='مثال: خبير HSE معتمد — 12 سنة خبرة ميدانية', max_length=150, verbose_name='الصفة المهنية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enrollment/formateurs/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل (يظهر على الموقع)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مكوّن',
                'verbose_name_plural': '👤 المكوّنون (الأساتذة)',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='offering',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='enrollment.formateur', verbose_name='المكوّن (اختياري)'),
        ),
    ]
