# Generated by Django 6.0.7 on 2026-07-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_formateur_offering_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='enrollment/offerings/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='تعليق (اختياري)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='enrollment.offering', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': '🖼️ معرض الصور (صور إضافية)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
