# Generated by Django 6.1 on 2026-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_alter_offeringattachment_options_formateur_cv_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الدراسة'), ('contacted', 'تم التواصل'), ('accepted', 'مقبول'), ('confirmed', 'مؤكد من طرف المشترك'), ('waitlisted', 'قائمة انتظار'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى من طرف المشترك')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
