# Generated by Django 6.1.1 on 2026-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_enrollment_cancelled_at_enrollment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('rejected', 'مرفوض')], default='active', help_text='pending: بانتظار موافقة الإدارة — active: مفعّل — rejected: مرفوض.', max_length=10, verbose_name='حالة الحساب'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='يُفعَّل فقط من طرف الإدارة أو المحاسب.', verbose_name='زبون VIP'),
        ),
    ]
