# Generated by Django 6.1.1 on 2026-09-03 10:42
"""Schema-only migration: adds the nullable Client.user link.

Data migration plan (TODO 1.2):
No backfill of existing rows is performed or planned here. `user` starts
NULL for every one of the ~existing Client rows. That is intentional and
permanent for legacy/walk-in clients created directly by admin staff
(via the seed commands or the Django admin) who never registered an
account — they keep operating exactly as before, with no login.

Going forward, this field is populated in exactly two places, both
added in later TODO tasks rather than here:
  - TODO 1.3 (public registration view): sets `client.user` at the same
    time it creates the new `User(is_active=False)` + `Client(...)` pair.
  - Any future "convert a legacy client to a login account" admin action
    would set `client.user` on an existing row after creating/linking a
    `User` for them — no such action exists yet.

If a real backfill is ever wanted for historical clients (e.g. bulk-
inviting old walk-ins to create accounts), it should be a separate,
explicit data migration (or management command) that creates inactive
`User` rows keyed off `Client.phone`/`Client.email` and links them —
never a default value on this field, since a shared/blank default would
silently collide across multiple Client rows on a OneToOneField.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_client_account_status_client_is_vip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='يُربط تلقائيا عند التسجيل عبر النموذج العمومي (المرحلة 1.3). فارغ لزبائن الحضور المباشر/الإدخال اليدوي القدامى الذين لا يملكون حساب دخول.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول'),
        ),
    ]
