# Generated by Django 6.1.1 on 2026-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='article_imposition',
            field=models.CharField(blank=True, max_length=30, verbose_name="رقم المادة الجبائية (Article d'imposition)"),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='البلدية / المدينة'),
        ),
        migrations.AddField(
            model_name='client',
            name='forme_juridique',
            field=models.CharField(blank=True, help_text='مثال: SARL، SPA، EURL، مؤسسة فردية...', max_length=100, verbose_name='الشكل القانوني'),
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='الشخص المسؤول عن الفوترة (البريد الإلكتروني)'),
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='الشخص المسؤول عن الفوترة (الاسم)'),
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الشخص المسؤول عن الفوترة (الهاتف)'),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم التعريف الجبائي (NIF)'),
        ),
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم التعريف الإحصائي (NIS)'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='client',
            name='rib',
            field=models.CharField(blank=True, help_text='20 رقما — يُستعمل في إعداد الفواتير/الحوالات.', max_length=30, verbose_name='رقم الحساب البنكي (RIB)'),
        ),
        migrations.AddField(
            model_name='client',
            name='tva_exempt',
            field=models.BooleanField(default=False, verbose_name='معفى من الرسم على القيمة المضافة (TVA)'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trade_register_number',
            field=models.CharField(blank=True, help_text='رقم السجل التجاري — يُستعمل أيضا كمرجع RC في المستخرجات المحاسبية.', max_length=60, verbose_name='رقم السجل التجاري (RC)'),
        ),
    ]
