# Generated by Django 6.1.1 on 2026-09-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_client_legal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار الزبائن VIP/المؤسسات — فوترة جماعية بالسعر لكل يوم تكوين.', max_digits=10, null=True, verbose_name='السعر لليوم الواحد (دج)'),
        ),
        migrations.AddField(
            model_name='offering',
            name='price_per_participant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار الزبائن VIP/المؤسسات — فوترة بالسعر لكل مشارك.', max_digits=10, null=True, verbose_name='السعر للمشارك الواحد (دج)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار التسجيل الفردي (تكوين تأهيلي طويل المدى بالأشهر).', max_digits=10, null=True, verbose_name='القيمة الشهرية (دج)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار التسجيل الفردي (تكوين تأهيلي طويل المدى بالأشهر).', max_digits=10, null=True, verbose_name='القيمة الإجمالية (دج)'),
        ),
    ]
