# Generated by Django 6.1.1 on 2026-09-05 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_offering_group_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('converted', 'تم تحويلها إلى طلب')], default='active', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='enrollment.client', verbose_name='الزبون')),
            ],
            options={
                'verbose_name': 'سلة',
                'verbose_name_plural': 'السلال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المشاركين')),
                ('billing_basis', models.CharField(blank=True, choices=[('per_day', 'حسب عدد أيام التكوين'), ('per_participant', 'حسب عدد المشاركين')], help_text='يُضبط فقط لسلال الزبائن VIP — يبقى فارغا لغير ذلك (مسار طلب عرض السعر).', max_length=20, verbose_name='أساس الفوترة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.cart', verbose_name='السلة')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='enrollment.offering', verbose_name='التخصص')),
                ('trainer', models.ForeignKey(blank=True, help_text='لا يُعرض ولا يُسمح باختياره إلا في سلال الزبائن VIP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='enrollment.formateur', verbose_name='المكوّن (اختياري — VIP فقط)')),
            ],
            options={
                'verbose_name': 'عنصر في السلة',
                'verbose_name_plural': 'عناصر السلة',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client',), name='unique_active_cart_per_client'),
        ),
    ]
