# Generated by Django 6.1.1 on 2026-09-05 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_cart_cartitem_cart_unique_active_cart_per_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='enrollment.client', verbose_name='الزبون')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='enrollment.offering', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'عنصر في قائمة الرغبات',
                'verbose_name_plural': 'قائمة الرغبات',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'offering')},
            },
        ),
    ]
