# Generated by Django 6.1.1 on 2026-09-05 11:14

import django.core.validators
import django.db.models.deletion
import enrollment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكدة'), ('cancelled', 'ملغاة')], default='pending', max_length=10, verbose_name='الحالة')),
                ('bon_de_commande', models.FileField(blank=True, null=True, upload_to=enrollment.models.proforma_bon_de_commande_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='بون دي كوماند')),
                ('bon_de_commande_original_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الأصلي للملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='enrollment.client', verbose_name='الزبون')),
            ],
            options={
                'verbose_name': 'فاتورة أولية (بروفورما)',
                'verbose_name_plural': '🧾 الفواتير الأولية (بروفورما)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_code', models.CharField(max_length=20, verbose_name='رمز التخصص')),
                ('offering_title', models.CharField(max_length=150, verbose_name='عنوان التخصص')),
                ('session_name', models.CharField(blank=True, max_length=120, verbose_name='الدورة')),
                ('trainer_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المكوّن')),
                ('billing_basis', models.CharField(choices=[('per_day', 'حسب عدد أيام التكوين'), ('per_participant', 'حسب عدد المشاركين')], max_length=20, verbose_name='أساس الفوترة')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المشاركين')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الوحدة (دج)')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المجموع (دج)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.proformainvoice', verbose_name='الفاتورة الأولية')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_items', to='enrollment.offering', verbose_name='التخصص')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_items', to='enrollment.formateur', verbose_name='المكوّن')),
            ],
            options={
                'verbose_name': 'بند في الفاتورة الأولية',
                'verbose_name_plural': 'بنود الفاتورة الأولية',
                'ordering': ['id'],
            },
        ),
    ]
