# Generated by Django 6.1.1 on 2026-09-05 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_proformainvoice_proformainvoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('priced', 'تم التسعير'), ('approved', 'معتمدة'), ('cancelled', 'ملغاة')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='enrollment.client', verbose_name='الزبون')),
            ],
            options={
                'verbose_name': 'طلب عرض سعر',
                'verbose_name_plural': '📋 طلبات عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_code', models.CharField(max_length=20, verbose_name='رمز التخصص')),
                ('offering_title', models.CharField(max_length=150, verbose_name='عنوان التخصص')),
                ('session_name', models.CharField(blank=True, max_length=120, verbose_name='الدورة')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المشاركين')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='enrollment.offering', verbose_name='التخصص')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.quoterequest', verbose_name='طلب عرض السعر')),
            ],
            options={
                'verbose_name': 'بند في طلب عرض السعر',
                'verbose_name_plural': 'بنود طلب عرض السعر',
                'ordering': ['id'],
            },
        ),
    ]
