# Generated by Django 6.1.1 on 2026-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0018_quoterequest_quoterequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[('per_day', 'حسب عدد أيام التكوين'), ('per_participant', 'حسب عدد المشاركين')], help_text='يضبطه المحاسب/الإدارة عند التسعير — فارغ إلى حين ذلك.', max_length=20, verbose_name='أساس الفوترة'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='التعريفة المخصّصة لهذا البند (يضبطها المحاسب/الإدارة).', max_digits=10, null=True, verbose_name='سعر الوحدة (دج)'),
        ),
    ]
