# Generated by Django 6.1.1 on 2026-09-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0019_quoterequestitem_billing_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='roster_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق قائمة المشاركين'),
        ),
        migrations.AddField(
            model_name='enrollmentnote',
            name='visible_to_client',
            field=models.BooleanField(default=False, help_text='عند التفعيل، تظهر هذه الملاحظة في مساحة الزبون. مخفية افتراضيا للحفاظ على خصوصية الملاحظات الداخلية.', verbose_name='مرئية للزبون'),
        ),
        migrations.CreateModel(
            name='EnrollmentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم (Prénom)')),
                ('last_name', models.CharField(max_length=50, verbose_name='اللقب (Nom)')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, verbose_name='الاسم بالعربية')),
                ('last_name_ar', models.CharField(blank=True, max_length=50, verbose_name='اللقب بالعربية')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='مكان الميلاد')),
                ('place_of_birth_ar', models.CharField(blank=True, max_length=100, verbose_name='مكان الميلاد (AR)')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('employer', models.CharField(blank=True, help_text='تُعبَّأ افتراضيا باسم مؤسسة الزبون عند الإنشاء، قابلة للتعديل لكل سطر.', max_length=200, verbose_name='جهة العمل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='enrollment.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'مشارك (قائمة المؤسسة)',
                'verbose_name_plural': 'المشاركون (قائمة المؤسسة)',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('enrollment', 'first_name', 'last_name')},
            },
        ),
    ]
