# Generated by Django 6.1.1 on 2026-09-13 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0020_phase10_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(verbose_name='التاريخ المقترح')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الطلب')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('reviewed', 'تمت المراجعة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_change_requests', to='enrollment.enrollment', verbose_name='التسجيل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة من طرف')),
            ],
            options={
                'verbose_name': 'طلب تغيير موعد الدورة',
                'verbose_name_plural': 'طلبات تغيير موعد الدورة',
                'ordering': ['-created_at'],
            },
        ),
    ]
