# Generated by Django 6.1.1 on 2026-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0022_offering_created_at_offering_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['-is_pinned', 'order', 'code'], 'verbose_name': 'عرض تكوين', 'verbose_name_plural': 'عروض التكوين'},
        ),
        migrations.AddField(
            model_name='offering',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='العروض المثبّتة تظهر دائما في مقدمة الكتالوج، قبل الترتيب/الفرز المختار.', verbose_name='مثبّت (يظهر أولا في الكتالوج)'),
        ),
    ]
