# Generated by Django 5.1.15 on 2026-09-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0023_alter_offering_options_offering_is_pinned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together=set(),
        ),
    ]
