# Generated by Django 5.1.15 on 2026-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0024_alter_offering_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='daily_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار التسجيل الفردي (تكوين قصير المدى بالأيام).', max_digits=10, null=True, verbose_name='القيمة اليومية (دج)'),
        ),
        migrations.AddField(
            model_name='offering',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='للتكوينات القصيرة المدى — بديل عن مدة الأشهر أعلاه.', null=True, verbose_name='مدة التكوين (أيام)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='للتكوينات طويلة المدى. اتركه فارغا إن كانت المدة تُحتسب بالأيام أدناه.', null=True, verbose_name='مدة التكوين (أشهر)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مسار التسجيل الفردي — تُحتسب تلقائيا من المدة والقيمة (بالأشهر أو بالأيام).', max_digits=10, null=True, verbose_name='القيمة الإجمالية (دج)'),
        ),
    ]
