"""
Django settings for eems_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a .env file at the project root, if it exists.
# Does nothing (no error) if the file is absent — safe to keep this call
# unconditional in every environment.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_)l*h!8sdkyvt1vz+6_pqvl3qzyejafazx5wt2vfe%lmr54a4e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "rest_framework",
    "pages",
    "enrollment",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "pages.middleware.VisitorCounterMiddleware",
]

ROOT_URLCONF = "eems_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eems_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# If POSTGRES_DB (or DB_NAME) is set — typically via a .env file loaded
# above — use PostgreSQL. Otherwise fall back to the local sqlite3 file,
# so the project still runs out of the box with zero configuration.

POSTGRES_DB_NAME = os.environ.get("POSTGRES_DB") or os.environ.get("DB_NAME")

if POSTGRES_DB_NAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB_NAME,
            "USER": os.environ.get("POSTGRES_USER")
            or os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD")
            or os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST")
            or os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT")
            or os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": 0,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ar"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "public"
STATICFILES_DIRS = [BASE_DIR / "pages" / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings — support@excellance-ms.dz mailbox (Secure SSL/TLS, recommended)
# Server: mail.excellance-ms.dz — SMTP (outgoing) port 465, authenticated, SSL.
# NOTE: EMAIL_HOST_PASSWORD default below ("system2026*") is the mailbox's
# initial password. Change it on the mail account and set EMAIL_HOST_PASSWORD
# in the .env file — never rely on the hardcoded fallback in production.
ADMINS = [("الإدارة", "support@excellance-ms.dz")]
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.excellance-ms.dz"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "support@excellance-ms.dz")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "system2026*")
EMAIL_TIMEOUT = 10  # seconds — never let a slow/unreachable mail server hang a request
DEFAULT_FROM_EMAIL = f"إيمس — الدعم <{EMAIL_HOST_USER}>"
SERVER_EMAIL = EMAIL_HOST_USER

# Django REST Framework settings

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",  # افتراضيا: كل شيء محمي إلا ما صُرّح بغير ذلك
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        # أضف TokenAuthentication أو JWT هنا إن كان هناك تطبيق موبايل/واجهة منفصلة الحقا
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "registration": "10/hour",  # حماية نقاط التسجيل العمومية من السبام
    },
}
